@startuml
class com.hyancy.eco_recicla_reto_1_grupo_7.domain.DataUseCase {
- FirebaseRepo repository
+ FirebaseFirestore getData()
+ FirebaseAuth getAuth()
+ FirebaseUser getCurrentUser()
}
class com.hyancy.eco_recicla_reto_1_grupo_7.domain.UserUseCase {
- FirebaseRepo repository
+ void createUser(String,Integer,String,String,Context)
+ void getUserData(String)
+ String getUidUser()
+ void logoutSesion()
}
class com.hyancy.eco_recicla_reto_1_grupo_7.domain.WasteUseCase {
- FirebaseRepo repository
+ void setWaste(String,String,String,String,String,double,int)
+ void getWasteByUserId(String,ArrayList<QueryDocumentSnapshot>,TextView,TextView,String)
+ Query getQuantityWasteByUser(String)
}
@enduml