@startuml
class CleanPoints {
~ ImageView btnCerrar
# void onCreate(Bundle)
- void initComponents()
- void listenersButtons()
- ArrayList<Intent> initIntents()
}


AppCompatActivity <|-- CleanPoints
@enduml