@startuml
class com.hyancy.eco_recicla_reto_1_grupo_7.ui.Challenge {
# void onCreate(Bundle)
}
class com.hyancy.eco_recicla_reto_1_grupo_7.ui.Statistic {
- ImageView categoriasBottomBar
- ImageView imageViewToolbar
- DrawerLayout drawerLayout
- NavigationView navigationView
- UserViewModel userViewModel
~ WasteViewModel wasteViewModel
- LineChart mLineChart
- HorizontalBarChart mHorizontalBarChar
- PieChart mPieChart
- BarChart mVerticalBarChart
- CategoriesModel categories
# void onCreate(Bundle)
- void setVerticalBarChart()
- void setPieChart()
- void setHorizontalBarChart()
- void setLineChart()
- void initComponents()
- void listenersMenuAppBar()
- ArrayList<Intent> initIntents()
- void logoutCurrentSesion()
- void setToolbar()
+ boolean onNavigationItemSelected(MenuItem)
- ArrayList<String> getXAxisValues()
- ArrayList<BarDataSet> getDataSet()
}
class com.hyancy.eco_recicla_reto_1_grupo_7.ui.Index {
- ImageButton consejos
- Button btnIniciarSesion
- FirebaseAuth mAuth
+ void onStart()
# void onCreate(Bundle)
- void initComponents()
- void listenersButtons()
- ArrayList<Intent> initIntents()
}
class com.hyancy.eco_recicla_reto_1_grupo_7.ui.ChallengeAchievements {
# void onCreate(Bundle)
}
class com.hyancy.eco_recicla_reto_1_grupo_7.ui.PrivacyPoliceTermsConditions {
~ Button btnAceptoTerminos
# void onCreate(Bundle)
- void initComponents()
- void listenersButtons()
- ArrayList<Intent> initIntents()
}
class com.hyancy.eco_recicla_reto_1_grupo_7.ui.WasteRegisterForm {
- Button btnCalculatePoints
- ImageView categoriasBottomBar
- EditText edtDescription
- DrawerLayout drawerLayout
- NavigationView navigationView
- ImageView imageViewToolbar
~ DatePicker calendar
- LinearLayout lnLayoutRegisterCancelButtons
~ TextView tvPoints
~ double totalPoints
- Spinner categoryWasteSpinner
- ArrayList<String> listCategories
- WasteViewModel wasteViewModel
- UserViewModel userViewModel
~ WasteModel wasteModel
~ Bundle bundle
# void onCreate(Bundle)
- void initComponents()
- void setlisteners()
- void listenersMenuAppBar()
- void calculateWastePoints()
+ void registerWaste(String,String,String,String,String,double,int)
- double calculatePoints(double,double,double)
- double calculateRecyclingFactor(String)
- double calculateEnvioronmentalFactor(String)
- void spinnerUI(CategoriesModel)
- void logoutCurrentSesion()
- void setToolbar()
- void setDateRegister()
- void setDateRegister_()
- ArrayList<Intent> initIntents()
- void showRegisterCancelButtons(String,String,String,String,String,double,int)
- void showCalculateButton()
- void showDialogCalendar()
- void showDialogCompleteDataForm()
- void clearComponents()
+ boolean onNavigationItemSelected(MenuItem)
}
class com.hyancy.eco_recicla_reto_1_grupo_7.ui.Login {
- Button btnLogin
- TextInputEditText userLogin
- ProgressBar progressBar
- FirebaseAuth mAuth
- TextView tvNoHaveCount
- UserViewModel userViewModel
+ void onStart()
# void onCreate(Bundle)
- void initComponents()
- void listenersButtons()
- ArrayList<Intent> initIntents()
- void showDialogFogottenPassword()
- void showDialogCompleteDataLogin()
}
class com.hyancy.eco_recicla_reto_1_grupo_7.ui.UserRegister {
~ FloatingActionButton btnCerrar
~ CheckBox cbxTerminosCondiciones
~ Button btnRegistrarUsuario
~ ProgressBar progressBar
~ TextView tvYaTieneCuenta
~ EditText edtName
~ UserViewModel userViewModel
~ DatasetViewModel datasetViewModel
~ UserModel userModel
+ void onStart()
# void onCreate(Bundle)
- void initComponents()
- void listenersButtons()
+ void createUser()
- void showDialogCompleteAll()
- void showDialogoRegistroCompleto()
- void showDialogContrasenaNoCoincide()
- void showDialogAceptaCondicionesYTerminos()
- void showDialogTerminosYCondicones()
- void showDialogAceptaPrivacidad()
- void showDialogPrivacidad()
- void showDialogCorreoNoCoinciden()
- void showDialogCorreoValido()
- void createUser(String,Integer,String,String,Context)
- ArrayList<Intent> initIntents()
- void clearComponents()
- boolean isValidLengthPassword(String,int,int)
- boolean isValidEmailFormat(String)
}
class com.hyancy.eco_recicla_reto_1_grupo_7.ui.Achievements {
# void onCreate(Bundle)
}
class com.hyancy.eco_recicla_reto_1_grupo_7.ui.AppInformation {
# void onCreate(Bundle)
}
class com.hyancy.eco_recicla_reto_1_grupo_7.ui.Category {
- SearchView searchFilterCategory
- CardView[] cardsLists
- TextView[] tvCardsList
- ImageView imageViewToolbar
- DrawerLayout drawerLayout
- NavigationView navigationView
- CardView cardAceites
- TextView tvCardAceites
- ImageView estadisticasBottomBar
- GridLayout gridLayoutCards
- WasteViewModel wasteViewModel
- UserViewModel userViewModel
- ArrayList<QueryDocumentSnapshot> wasteList
# void onCreate(Bundle)
- void initComponents()
- TextView[] initTvCardsList()
- CardView[] initCardsList()
- void listenersCards()
- void listenersMenuAppBar()
- void filterCard()
- void searchFilterListener(String)
- void showDialogCard(String)
+ Integer getTotalPoints(ArrayList<QueryDocumentSnapshot>)
- double getTotalQuantity(ArrayList<QueryDocumentSnapshot>)
- ArrayList<Intent> initIntents()
- void logoutCurrentSesion()
- void setToolbar()
+ boolean onNavigationItemSelected(MenuItem)
}
class com.hyancy.eco_recicla_reto_1_grupo_7.ui.Tips {
- ImageView categoriasBottomBar
- ImageView imageViewToolbar
~ Toolbar toolbar
- DrawerLayout drawerLayout
- NavigationView navigationView
- LinearLayout lnrLMenuBottomBar
- View backgroundBottomBar
- FirebaseAuth mAuth
- FirebaseUser currentUser
- UserViewModel userViewModel
- DatasetViewModel datasetViewModel
- CardView consejoAceite
# void onCreate(Bundle)
- void initComponents()
- void showMenuBottomAppBar()
- void listenersMenuAppBar()
- void listenersCards()
- ArrayList<Intent> initIntents()
- void logoutCurrentSesion()
- void setToolbar()
+ void showConsejoAceite()
+ void showConsejoPlastico()
+ void showConsejoCompost()
+ void showConsejoRopa()
+ boolean onNavigationItemSelected(MenuItem)
}
class com.hyancy.eco_recicla_reto_1_grupo_7.ui.CleanPoints {
~ ImageView btnCerrar
# void onCreate(Bundle)
- void initComponents()
- void listenersButtons()
- ArrayList<Intent> initIntents()
}
class com.hyancy.eco_recicla_reto_1_grupo_7.ui.Main {
- Button btnCategorias
- ImageView imageViewToolbar
- DrawerLayout drawerLayout
- NavigationView navigationView
- TextView tvUserCurrent
- FirebaseAuth auth
- FirebaseUser currentUser
- UserViewModel userViewModel
# void onCreate(Bundle)
- void initComponents()
- void listenersButtons()
- ArrayList<Intent> initIntents()
- void showCurrentSesion()
- void logoutCurrentSesion()
- void setToolbar()
+ boolean onNavigationItemSelected(MenuItem)
}


androidx.appcompat.app.AppCompatActivity <|-- com.hyancy.eco_recicla_reto_1_grupo_7.ui.Challenge
com.hyancy.eco_recicla_reto_1_grupo_7.ui.OnNavigationItemSelectedListener <|.. com.hyancy.eco_recicla_reto_1_grupo_7.ui.Statistic
androidx.appcompat.app.AppCompatActivity <|-- com.hyancy.eco_recicla_reto_1_grupo_7.ui.Statistic
androidx.appcompat.app.AppCompatActivity <|-- com.hyancy.eco_recicla_reto_1_grupo_7.ui.Index
androidx.appcompat.app.AppCompatActivity <|-- com.hyancy.eco_recicla_reto_1_grupo_7.ui.ChallengeAchievements
androidx.appcompat.app.AppCompatActivity <|-- com.hyancy.eco_recicla_reto_1_grupo_7.ui.PrivacyPoliceTermsConditions
com.hyancy.eco_recicla_reto_1_grupo_7.ui.OnNavigationItemSelectedListener <|.. com.hyancy.eco_recicla_reto_1_grupo_7.ui.WasteRegisterForm
androidx.appcompat.app.AppCompatActivity <|-- com.hyancy.eco_recicla_reto_1_grupo_7.ui.WasteRegisterForm
androidx.appcompat.app.AppCompatActivity <|-- com.hyancy.eco_recicla_reto_1_grupo_7.ui.Login
androidx.appcompat.app.AppCompatActivity <|-- com.hyancy.eco_recicla_reto_1_grupo_7.ui.UserRegister
androidx.appcompat.app.AppCompatActivity <|-- com.hyancy.eco_recicla_reto_1_grupo_7.ui.Achievements
androidx.appcompat.app.AppCompatActivity <|-- com.hyancy.eco_recicla_reto_1_grupo_7.ui.AppInformation
com.hyancy.eco_recicla_reto_1_grupo_7.ui.OnNavigationItemSelectedListener <|.. com.hyancy.eco_recicla_reto_1_grupo_7.ui.Category
androidx.appcompat.app.AppCompatActivity <|-- com.hyancy.eco_recicla_reto_1_grupo_7.ui.Category
com.hyancy.eco_recicla_reto_1_grupo_7.ui.OnNavigationItemSelectedListener <|.. com.hyancy.eco_recicla_reto_1_grupo_7.ui.Tips
androidx.appcompat.app.AppCompatActivity <|-- com.hyancy.eco_recicla_reto_1_grupo_7.ui.Tips
androidx.appcompat.app.AppCompatActivity <|-- com.hyancy.eco_recicla_reto_1_grupo_7.ui.CleanPoints
com.hyancy.eco_recicla_reto_1_grupo_7.ui.OnNavigationItemSelectedListener <|.. com.hyancy.eco_recicla_reto_1_grupo_7.ui.Main
androidx.appcompat.app.AppCompatActivity <|-- com.hyancy.eco_recicla_reto_1_grupo_7.ui.Main
@enduml